### ISSUE TITLE
Is it possible to change the font-size?

### ISSUE THREAD

**Issue by zhiiwg** [atom/markdown-preview#135]
In high-dpi displays the font size is too small.
And it seems no place to set it

**Comment by mp4096** [comment]
Just to keep @envygeeks' answer up to date: Current package version requires `.markdown-preview.markdown-preview { ... }`:
```CSS
.markdown-preview.markdown-preview {
 &, h4, h5, h6 {
   font-size: font-size;
  }

  h1 { font-size: font-size; }
  h2 { font-size: font-size; }
  h3 { font-size: font-size; }
}
```
See `README.md`
