### ISSUE TITLE
Show horizontal rule when not using Github mode

### ISSUE THREAD

**Issue by pradyunsg** [atom/markdown-preview#267]
Currently, when not using the Github mode, horizontal rules are not rendered. They should be.

![screenshot](https://cloud.githubusercontent.com/assets/3275593/8396876/687427d0-1dd6-11e5-9387-4a9dd200c347.png)

Running Atom 1.0.0, markdown-preview 0.150.0. 
Live update: :white_check_mark: 
Grammers: default
Break on single newline: :white_check_mark: 

If it's related, I'm using One Light UI and syntax. My custom stylesheet is 

```css
atom-text-editor::shadow .indent-guide {
    box-shadow: inset 1px 0 0 rgb(230, 230, 230);
}
```
