### ISSUE TITLE
Black/dark design?

### ISSUE THREAD

**Issue by rugk** [atom/markdown-preview#296]
I'd like to use a black design for the markdown preview. (otherwise this is just a too strong contrast)

I've tried it with this simple CSS tweak, but it does not really looks such nice and it seems I have to adjust much more:
```less
.markdown-preview {
  color: #ffffff;
  background-color: #000000;
}
```

E.g. tables are still white and I don't really need such a dark black.

In https://github.com/atom/markdown-preview/issues/293#issuecomment-133168760 I've seen @hemraker uses one.
I think at least you, @hemraker, have a nicer solution for this.
