### ISSUE TITLE
Dosen't rendered the bottom part of file 

### ISSUE THREAD

**Issue by taiyoslime** [atom/markdown-preview#358]
#### description
Markdown-preview dosen't rendered the bottom part of file .
Here is a image showing issue.

This file is 626-lines long ,but only 432-lines has rendered.

<img width="1068" alt="ss 2016-01-06 11 25 53" src="https://cloud.githubusercontent.com/assets/11515982/12133381/606258cc-b468-11e5-80a0-c2491b324bea.png">

**Atom version:**  [ 1.3.2 ]
**Markdown-preview version:** [ 0.156.1 ]
**OS and version:** [ Mac OS X Yosemite v 10.10.2 ]

**Comment by 50Wliu** [comment]
@simurai could this be another manifestation of the "text suddenly stops appearing" bug in the One themes?

**Comment by simurai** [comment]
Yes, most likely. That bug can be narrowed down to:

1. Only happens with `One` themes.
2. Only happens on retina (hi res) screens.

And based on @taiyoslime's screenshot, it looks like it matches those 2 points.

It's fixed part of https://github.com/atom/one-dark-ui/pull/112. But as a temporary fix, you can add the following to your `styles.less` with:

```less
// Temporarily fixes page rendering from being cut off in the One themes.
.tree-view::before {
  transform: none;
}
```
