### ISSUE TITLE
Wrong image orientation

### ISSUE THREAD

**Issue by Asoul** [atom/markdown-preview#390]
I got wrong orientation in markdown preview, so I tried to fix this by adding css style.

```css
<style>
img {
  image-orientation: from-image;
}
</style>
```
And found the [image-orientation](https://developer.mozilla.org/en-US/docs/Web/CSS/image-orientation) property is not currently supported by [Chrome](http://caniuse.com/#feat=css-image-orientation).

Is this the point that atom can not support for correcting the image orientation right now?
