### ISSUE TITLE
Code block height in Preview is higher, should be symmetrical like it is here on github

### ISSUE THREAD

**Issue by marcofugaro** [atom/markdown-preview#479]
How it is actually

![](http://i.imgur.com/0okQCar.png)

How it is on github

![](http://i.imgur.com/QZiuOR9.png)

You can see there is more padding on the bottom making it look odd.

**Comment by bmda** [comment]
Working around this by overriding the bottom padding value in styles.css and setting it to zero improves the imbalance, but the space at the bottom is still larger than it should be:

```css
.markdown-preview.markdown-preview {
  atom-text-editor {
    padding: 1em 1em 0em 1em;
  }
}
```

Increasing the space at the top will balance it out (and looks best, in my opinion), but obviously doesn't solve the problem perfectly:

```css
.markdown-preview.markdown-preview {
  atom-text-editor {
     padding: 1.5em 1em 0em 1em;
  }
}
```
