### ISSUE TITLE
Specifying rendered font via settings?

### ISSUE THREAD

**Issue by thbar** [atom/markdown-preview#86]
I find that fonts like "Cochin" work well when writing blog posts etc.

I digged in a bit and found that I could replace Helvetica here:

https://github.com/atom/markdown-preview/blob/master/stylesheets/markdown-preview.less#L3

Maybe being able to inject a setting here would be nice?

What do you think?

**Comment by azat-co** [comment]
@izuzak @thbar nice! I also recommend adding these styles to the .less:

```
.markdown-preview, .source.gfm {
  font-family: "Georgia";
}
```

This will show markdown text non-monospaced in the editor!

**Comment by azat-co** [comment]
For some reason my stylesheet is not picking up the changes though

**Comment by simurai** [comment]
> @azat-co For some reason my stylesheet is not picking up the changes though

Do you have the `Use GitHub.com style` enabled in the package settings? It needs a stronger selector. Also for `.source.gfm`. This should work:

```less
.markdown-preview.markdown-preview,
atom-text-editor::shadow .source.gfm {
  font-family: "Georgia";
}
```

**Comment by azat-co** [comment]
@simurai nice. It did the trick! Thank you.

I ended up with these styles:

```css
.markdown-preview.markdown-preview,
atom-text-editor::shadow .line .source.gfm {
  font-family: "Baskerville";
  color: #ddd;
}

.markdown-preview.markdown-preview,
atom-text-editor::shadow .line .source.gfm .code.markup, atom-text-editor::shadow .line .markup.raw.gfm {
  font-family: "Inconsolata", "Source Code Pro";
  color: #999;
}
```
